#kubectl alias
alias ksn='kubectl config set-context $(kubectl config current-context) --namespace='
alias kgpo='kubectl get pods'
alias kgno='kubectl get nodes'
alias kging='kubectl get ingress'
alias kgsvc='kubectl get service'
alias kgpvc='kubectl get pvc'
alias kgdep='kubectl get deployment'
alias kgsc='kubectl get storageclass'
alias kgpv='kubectl get pv'
alias kgss='kubectl get statefulset'
alias kgr='kubectl get role'
alias kgsa='kubectl get serviceAccounts'
alias kgrb='kubectl get rolebindings'
alias kgcr='kubectl get clusterroles'
alias kgcrb='kubectl get clusterrolebindings'
alias kgsec='kubectl get secret'
alias kgcm='kubectl get configmap'
alias kgpoall='kubectl get pods --all-namespaces'
alias kgingall='kubectl get ingress --all-namespaces'
alias kgsvcall='kubectl get service --all-namespaces'
alias kgpvcall='kubectl get pvc --all-namespaces'
alias kgscall='kubectl get storageclass --all-namespaces'
alias kgpvall='kubectl get pv --all-namespaces'
alias kgdepall='kubectl get deployment --all-namespaces'
alias kgssall='kubectl get statefulset --all-namespaces'
alias kgrall='kubectl get role --all-namespaces'
alias kgsaall='kubectl get serviceAccounts --all-namespaces'
alias kgrball='kubectl get rolebindings --all-namespaces'
alias kgsecall='kubectl get secret --all-namespaces'
alias kgsecall='kubectl get secret --all-namespaces'
alias kgcmall='kubectl get configmap --all-namespaces'
alias kdpo='kubectl describe pods'
alias kdno='kubectl describe nodes'
alias kding='kubectl describe ingress'
alias ksysding='kubectl config set-context $(kubectl config current-context) --namespace=ingress'
alias kdpv='kubectl describe pvc'
alias ksysdpv='kubectl config set-context $(kubectl config current-context) --namespace=pvc'
alias kdcr='kubectl describe clusterrole'
alias ksyscr='kubectl config set-context $(kubectl config current-context) --namespace=clusterrole'
alias kdcrb='kubectl describe clusterrolebinding'
alias ksyscrb='kubectl config set-context $(kubectl config current-context) --namespace=clusterrolebinding'
alias kdsvc='kubectl describe service'
alias kdpvc='kubectl describe pvc'
alias kdsc='kubectl describe storageclass'
alias kdpv='kubectl describe pv'
alias kddep='kubectl describe deployment'
alias kdss='kubectl describe statefulset'
alias kdr='kubectl describe role'
alias kdsa='kubectl describe serviceAccounts'
alias kdrb='kubectl describe rolebindings'
alias kdsec='kubectl describe secret'
alias kdcm='kubectl describe configmap'
alias klo='kubectl logs -f'

alias ku='kubectl --insecure-skip-tls-verify'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi
source <(kubectl completion bash)
source <(helm completion bash)