apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  volumeName: "plex-data-nfs"