---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-appdata
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  volumeName: "grafana-appdata"