apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-appdata
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  volumeName: "plex-appdata"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  volumeName: "plex-media"