apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.10.120
    path: "/media"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-appdata
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.10.120
    path: "/plex"