apiVersion: v1
kind: Service
metadata:
  labels:
    app: plex
  name: plex
  namespace: apps
spec:
  ports:
  - name: http
    port: 32400
    protocol: TCP
    targetPort: 32400
  selector:
    app: plex
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: plex
  name: plex-nodeport
  namespace: apps
spec:
  ports:
    - nodePort: 32400
      port: 32400
      protocol: TCP
      targetPort: 32400
  selector:
    app: plex
  type: NodePort