apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-plex
  namespace: apps
spec:
  selector:
    matchLabels:
      app: docker-plex
  template:
    metadata:
      labels:
        app: docker-plex
    spec:
      nodeName: k8s-home-node1
      containers:
      - image: jaymoulin/plex:1.15.2-aarch64
        imagePullPolicy: IfNotPresent
        name: docker-plex
        ports:
          - name: debug
            containerPort: 32600
          - name: http
            containerPort: 32400
          - name: https
            containerPort: 32443
        env:
          - name: TZ
            value: "Europe/Berlin"
          - name: PLEX_CLAIM
            value: "***"
          - name: PMS_INTERNAL_ADDRESS
            value: https://plex.sandermann.cloud:443
        volumeMounts:
          - mountPath: /media
            name: debug-media
          - mountPath: /root/Library
            name: debug-library
      volumes:
        - name: debug-media
          persistentVolumeClaim:
            claimName: plex-docker-debug-media
        - name: debug-library
          persistentVolumeClaim:
            claimName: plex-docker-debug-library
