apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-docker-debug-media
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.10.120
    path: "/debug/media"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-docker-debug-library
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.10.120
    path: "/debug/library"